@startuml
top to bottom direction
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

SHOW_PERSON_OUTLINE()

Person(call, "Сотрудник кол-центра")
Person_Ext(callPart, "Сотрудник партнерского кол-центра")


System(site, "Сайт")
System(abs, "АБС")
System_Ext(sftp, "SFTP-сервер")


Rel(site, abs, "Чтение информации о ставках, депозитах")
Rel(abs, sftp, "Выгружает ставки")
Rel(call, site, "Просматривает актуальные ставки")
Rel(callPart, sftp, "Скачивает файл со ставками")

@enduml
